---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        example: 1
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: User found
        '404':
          description: Not found
  "/api/v1/users/{id}/following_sleep_histories":
    get:
      summary: Retrieves sleep histories from user followed by current user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        example: 1
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '404':
          description: Not found
  "/api/v1/users/{id}/fall_asleep":
    post:
      summary: Fall asleep
      tags:
      - Users
      parameters:
      - name: id
        in: path
        example: 1
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Sleep history created
        '404':
          description: Not found
        '422':
          description: Unprocessable entity
  "/api/v1/users/{id}/wake_up":
    post:
      summary: Wake up
      tags:
      - Users
      parameters:
      - name: id
        in: path
        example: 1
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
  "/api/v1/users/{id}/follow/{following_id}":
    post:
      summary: Follow
      tags:
      - Users
      parameters:
      - name: id
        in: path
        example: 1
        required: true
        schema:
          type: integer
      - name: following_id
        in: path
        example: 2
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
  "/api/v1/users/{id}/unfollow/{following_id}":
    post:
      summary: Unfollow
      tags:
      - Users
      parameters:
      - name: id
        in: path
        example: 1
        required: true
        schema:
          type: integer
      - name: following_id
        in: path
        example: 2
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
        '400':
          description: Bad request
        '404':
          description: Not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:9913
